import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

import { headingFont, bodyFont } from "./fonts";

export const metadata: Metadata = {
  title: "Sliding Signin Signup",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      className={`${headingFont.variable} ${bodyFont.variable}`}
    >
      <body className="font-body antialiased bg-white text-gray-900">
        {children}
      </body>
    </html>
  );
}



